#!/usr/bin/bash

# List of packages
packages=(
  swaync
  hyprpicker
  satty
  pamixer
  ttf-fira-code
  ttf-nerd-fonts-symbols
  noto-fonts-emoji
  google-chrome
  mattermost-desktop
  ttf-font-awesome
  less
  ttf-nerd-fonts-symbols
  hyprshot
  ly
  waybar
  waypaper
  hyprpaper
  hyprsunset
  hyprlock
  udiskie
  wlogout
  python-pywal
  nwg-look
  rofi-lbonn-wayland-git
  rofi-calc
  rofi-emoji
  pipes.sh
  nvim
  nautilus
  eog
  evince
  decibels
  blueberry
  network-manager-applet
  asciiquarium
  sl
  lolcat
  bibata-cursor-theme
  adw-gtk-theme
  swww
  vesktop-bin
  nextcloud-talk-desktop-bin
  brave-bin
  postman-bin
  onlyoffice-bin
  zoxide
  wl-clipboard
  vlc
  slurp
  opencode
  nvm
  obs-studio
  nwg-look
  nvidia-utils

)

sudo pacman -Sy --noconfirm

# Install packages
for pkg in "${packages[@]}"; do
  echo "Installing $pkg..."
  if ! pacman -Qq "$pkg" &>/dev/null; then
    yay -S --noconfirm --needed "$pkg"
  fi
  echo "$pkg is already installed"
done

echo "All packages installed."
