#!/usr/bin/bash

# List of packages
packages=(
  ttf-fira-code
  ttf-nerd-fonts-symbols
  noto-fonts-emoji
  google-chrome
  mattermost-desktop
  ttf-font-awesome
  less
  ttf-nerd-fonts-symbols
  hyprshot
  ly
  waybar
  waypaper
  hyprpaper
  hyprsunset
  hyprlock
  udiskie
  wlogout
  python-pywal16
  nwg-look
  rofi-lbonn-wayland-git
  rofi-calc
  rofi-emoji
  pipes.sh
  nvim
  nautilus
  eog
  evince
  decibels
  blueberry
  pavucontrol
  network-manager-applet
  asciiquarium
  sl
  lolcat
  bibata-cursor-theme
  adw-gtk-theme
)

sudo pacman -Sy --noconfirm

# Install packages
for pkg in "${packages[@]}"; do
  echo "Installing $pkg..."
  if ! pacman -Qq "$pkg" &>/dev/null; then
    yay -S --noconfirm --needed "$pkg"
  fi
  echo "$pkg is already installed"
done

echo "All packages installed."
