#!/usr/bin/env bash

curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install nodejs npm -y
npm config set prefix ~/.local/npm
npm i -g n
n lts

curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash
