#!/usr/bin/env bash
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa

sudo apt install python3.10 python3.10-venv python3.10-dev python3.11 \
python3.11-dev python3.11-venv python3.12 python3.12-dev python3.12-venv
