--- Dynamic Animations (active set)
hl.curve("wind",   { type = "bezier", points = {{0.05, 0.9},  {0.1,  1.05}} })
hl.curve("winIn",  { type = "bezier", points = {{0.1,  1.1},  {0.1,  1.1}} })
hl.curve("winOut", { type = "bezier", points = {{0.3, -0.3},  {0,    1}} })
hl.curve("liner",  { type = "bezier", points = {{1,    1},    {1,    1}} })

hl.animation({ leaf = "windows",     enabled = true, speed = 6,  bezier = "wind",  style = "slide"  })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 6,  bezier = "winIn", style = "slide"  })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 5,  bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5,  bezier = "wind",   style = "slide" })
hl.animation({ leaf = "border",      enabled = true, speed = 1,  bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner",  style = "loop"  })
hl.animation({ leaf = "fade",        enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,  bezier = "wind" })

--- Alternative: Static Animations
-- hl.curve("easeOutQuint",   { type = "bezier", points = {{0.23, 1},    {0.32, 1}    } })
-- hl.curve("easeInOutCubic", { type = "bezier", points = {{0.65, 0.05}, {0.36, 1}    } })
-- hl.curve("linear",         { type = "bezier", points = {{0, 0},       {1, 1}       } })
-- hl.curve("almostLinear",   { type = "bezier", points = {{0.5, 0.5},   {0.75, 1}    } })
-- hl.curve("quick",          { type = "bezier", points = {{0.15, 0},    {0.1, 1}     } })
--
-- hl.animation({ leaf = "global",        enabled = true, speed = 5,    bezier = "default" })
-- hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
-- hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
-- hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
-- hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
-- hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
-- hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
-- hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
-- hl.animation({ leaf = "workspaces",    enabled = true, speed = 1,    bezier = "easeOutQuint" })
-- hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1,    bezier = "easeOutQuint" })

--- Alternative: Moving Animations
-- hl.curve("overshot",   { type = "bezier", points = {{0.05, 0.9}, {0.1,  1.05}} })
-- hl.curve("smoothOut",  { type = "bezier", points = {{0.5,  0},   {0.99, 0.99}} })
-- hl.curve("smoothIn",   { type = "bezier", points = {{0.5, -0.5}, {0.68, 1.5}} })
--
-- hl.animation({ leaf = "windows",     enabled = true, speed = 5, bezier = "overshot", style = "slide" })
-- hl.animation({ leaf = "windowsOut",  enabled = true, speed = 3, bezier = "smoothOut" })
-- hl.animation({ leaf = "windowsIn",   enabled = true, speed = 3, bezier = "smoothOut" })
-- hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "smoothIn", style = "slide" })
-- hl.animation({ leaf = "border",      enabled = true, speed = 5, bezier = "default" })
-- hl.animation({ leaf = "fade",        enabled = true, speed = 5, bezier = "smoothIn" })
-- hl.animation({ leaf = "fadeDim",     enabled = true, speed = 5, bezier = "smoothIn" })
-- hl.animation({ leaf = "workspaces",  enabled = true, speed = 6, bezier = "default" })
