hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waypaper --random --backend awww")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprsunset --temperature 5000")
    hl.exec_cmd("swaync")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("systemctl --user restart kanata.service")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl dispatch moveworkspacetomonitor 1 HDMI-A-1")
    hl.exec_cmd("hyprctl dispatch moveworkspacetomonitor 2 DP-1")
end)
